# Generated by Django 4.2.23 on 2026-02-03 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='available_sizes',
            field=models.CharField(default=django.utils.timezone.now, help_text="Comma-separated sizes (e.g., S,M,L,XL). Use 'ONE SIZE' for one-size items.", max_length=100),
            preserve_default=False,
        ),
    ]
