# Generated by Django 4.2.23 on 2026-02-03 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_cartitem_size_orderitem_size_product_available_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_sizes',
        ),
        migrations.AddField(
            model_name='order',
            name='customer_size',
            field=models.CharField(blank=True, help_text='e.g., M, L, XL, or measurements', max_length=50, verbose_name='Size/Measurement'),
        ),
    ]
